version: '2'

services:

  useraction:
      build: ./
      command: python useraction_sync.py
      networks:
        - outside

networks:
  outside:
    external:
      name: useractionelk_elk_user_action
